import { chromium } from 'playwright';
import fs from 'node:fs';
const positions = JSON.parse(fs.readFileSync('data/positions.json', 'utf8')).positions;
const counts = {};
for (const p of positions) if (p.question_ids.includes('q26')) counts[p.commenter_id] = (counts[p.commenter_id] || 0) + 1;
const cid = Object.entries(counts).sort((a, b) => b[1] - a[1])[0][0];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await b.newPage({ viewport: { width: 1200, height: 900 } });
await page.route(/fonts\.g(oogleapis|static)\.com/, r => r.abort());
await page.goto('http://127.0.0.1:8123/#q26', { waitUntil: 'networkidle' });
await page.waitForTimeout(500);
const card = page.locator(`#q26-panel .pc[data-commenter="${cid}"]`);
await card.screenshot({ path: '/tmp/claude-0/-home-user-probable-telegram/0e2912e4-fb8e-53eb-92a2-84ae09462a2f/scratchpad/card.png' });
console.log(cid, counts[cid]);
await b.close();
